"""
Django settings for miat project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# NOTE: Removed ASGI imports that were incorrectly placed here.
# Those imports belong in asgi.py only — not in settings.py.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Security ──────────────────────────────────────────────────────────────────

SECRET_KEY = 'django-insecure-ak1=3qc=+ibpp8lm4$45)1^v*-^xukr0g=ksdk9lmqwo4mlyrf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Fix: was [] which causes CommandError when daphne or channels is active
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# ── Installed Apps ────────────────────────────────────────────────────────────
# daphne MUST be first — enables WebSocket support on runserver

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'django_q',
    'scanner',
]


# ── Middleware ────────────────────────────────────────────────────────────────

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ── URL and ASGI ──────────────────────────────────────────────────────────────

ROOT_URLCONF     = 'miat.urls'
ASGI_APPLICATION = 'miat.asgi.application'
WSGI_APPLICATION = 'miat.wsgi.application'


# ── Templates ─────────────────────────────────────────────────────────────────

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ── Database ──────────────────────────────────────────────────────────────────

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ── Password validation ───────────────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ── Internationalisation ──────────────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True


# ── Static files ──────────────────────────────────────────────────────────────

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── Django-Q2 ─────────────────────────────────────────────────────────────────

Q_CLUSTER = {
    'name':        'miat',
    'workers':     2,
    'timeout':     600,
    'retry':       720,
    'queue_limit': 50,
    'bulk':        10,
    'orm':         'default',
    'sync':        False,
}


# ── Django Channels — channel layer ───────────────────────────────────────────
# In-memory layer: no Redis needed for development.
# For production with multiple workers switch to RedisChannelLayer.

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {'hosts': [('127.0.0.1', 6379)]},
    }
}


# ── JWT configuration ─────────────────────────────────────────────────────────

JWT_PRIVATE_KEY_PATH    = BASE_DIR / 'certs' / 'server.key'
JWT_PUBLIC_KEY_PATH     = BASE_DIR / 'certs' / 'server_pub.key'
JWT_CERT_PATH           = BASE_DIR / 'certs' / 'server.crt'
JWT_ACCESS_EXPIRY_MINUTES  = 15
JWT_REFRESH_EXPIRY_MINUTES = 1440


# ── Agent registration key ────────────────────────────────────────────────────

AGENT_REGISTRATION_KEY = os.environ.get(
    'AGENT_REGISTRATION_KEY',
    'change-this-to-something-strong'
)


# ── Scan cache ────────────────────────────────────────────────────────────────

SCAN_CACHE_TTL = 3600


# ── Auth redirects ────────────────────────────────────────────────────────────

LOGIN_REDIRECT_URL = '/'
LOGIN_URL          = '/accounts/login/'