# Generated by Django 5.2.13 on 2026-05-03 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='IP address, hostname, or CIDR range e.g. 192.168.1.0/24', max_length=255)),
                ('scan_profile', models.CharField(choices=[('fast', 'Fast (top 100 ports)'), ('default', 'Default (top 1000 ports)'), ('deep', 'Deep (all ports + OS detection)'), ('ping', 'Ping sweep (hosts only)')], default='default', max_length=20)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cached', 'Cached')], default='pending', max_length=20)),
                ('cache_hit', models.BooleanField(default=False)),
                ('overall_risk', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('total_hosts', models.IntegerField(default=0)),
                ('hosts_up', models.IntegerField(default=0)),
                ('total_open_ports', models.IntegerField(default=0)),
                ('high_severity_count', models.IntegerField(default=0)),
                ('medium_severity_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cached_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cache_copies', to='scanner.scanrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Request',
                'verbose_name_plural': 'Scan Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('os_detected', models.CharField(blank=True, default='N/A', max_length=255)),
                ('os_accuracy', models.IntegerField(default=0)),
                ('host_risk', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('open_port_count', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='scanner.scanrequest')),
            ],
            options={
                'verbose_name': 'Host Result',
                'verbose_name_plural': 'Host Results',
                'ordering': ['ip_address'],
                'unique_together': {('scan', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='PortFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('service_name', models.CharField(blank=True, default='', max_length=100)),
                ('service_product', models.CharField(blank=True, default='', max_length=255)),
                ('service_version', models.CharField(blank=True, default='', max_length=255)),
                ('service_cpe', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info'), ('NONE', 'None')], default='INFO', max_length=10)),
                ('risk_note', models.TextField(blank=True, default='')),
                ('is_critical_alert', models.BooleanField(default=False)),
                ('alert_message', models.CharField(blank=True, default='', max_length=500)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanner.hostresult')),
            ],
            options={
                'verbose_name': 'Port Finding',
                'verbose_name_plural': 'Port Findings',
                'ordering': ['port'],
                'unique_together': {('host', 'port', 'protocol')},
            },
        ),
    ]
