# Generated by Django 5.2.13 on 2026-05-11 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, help_text='Unique identifier for this agent, e.g. barc-lab-01', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('auth_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret_key', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-registered_at'],
            },
        ),
    ]
