# Generated by Django 5.2.13 on 2026-05-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('date_seed', 'Date-Seeded SHA-256'), ('xor_lcg', 'XOR + LCG (Conficker-style)'), ('wordlist', 'Wordlist Combination')], default='date_seed', max_length=20)),
                ('total_queries', models.IntegerField(default=0)),
                ('rate_per_sec', models.FloatField(default=1.0)),
                ('dns_server', models.CharField(blank=True, default='system', max_length=64)),
                ('seed_date', models.DateField(blank=True, null=True)),
                ('nxdomain_count', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('timeout_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('nxdomain_ratio', models.FloatField(default=0.0)),
                ('avg_entropy', models.FloatField(default=0.0)),
                ('max_entropy', models.FloatField(default=0.0)),
                ('min_entropy', models.FloatField(default=0.0)),
                ('duration_sec', models.FloatField(default=0.0)),
                ('ids_detected', models.BooleanField(blank=True, null=True)),
                ('ids_detection_notes', models.TextField(blank=True, default='')),
                ('domains_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dga_results', to='scanner.agent')),
            ],
            options={
                'verbose_name': 'DGA Result',
                'verbose_name_plural': 'DGA Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
