# Generated by Django 5.2.13 on 2026-05-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_dgaresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExfilResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('dns', 'DNS Tunnelling'), ('http', 'HTTP Header Injection'), ('icmp', 'ICMP Payload Stuffing')], default='dns', max_length=10)),
                ('profile', models.CharField(choices=[('burst', 'Burst (maximum speed)'), ('slow_drip', 'Slow Drip (timed intervals)'), ('jitter', 'Jitter (random delays)')], default='burst', max_length=20)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('total_chunks', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('duration_sec', models.FloatField(default=0.0)),
                ('avg_interval_sec', models.FloatField(default=0.0)),
                ('ids_severity', models.CharField(blank=True, max_length=20)),
                ('ids_signatures', models.JSONField(default=list)),
                ('ids_detected', models.BooleanField(blank=True, null=True)),
                ('ids_detection_notes', models.TextField(blank=True, default='')),
                ('packets_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exfil_results', to='scanner.agent')),
            ],
            options={
                'verbose_name': 'Exfil Result',
                'verbose_name_plural': 'Exfil Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
