# Generated by Django 5.2.13 on 2026-06-08 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_exfilresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostresult',
            options={'ordering': ['ip_address']},
        ),
        migrations.AlterModelOptions(
            name='portfinding',
            options={'ordering': ['port']},
        ),
        migrations.AlterModelOptions(
            name='scanrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanrequest',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to='scanner.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='exfilresult',
            name='profile',
            field=models.CharField(choices=[('burst', 'Burst'), ('slow_drip', 'Slow Drip'), ('jitter', 'Jitter')], default='burst', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='cached_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanrequest'),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='scan_profile',
            field=models.CharField(choices=[('fast', 'Fast (top 100 ports)'), ('default', 'Default (top 1000 ports)'), ('deep', 'Deep (all ports + OS)'), ('ping', 'Ping sweep')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='target',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ModuleTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier threaded through every layer of the dispatch pipeline. Included in the WebSocket command args so the agent can echo it back in the telemetry POST, allowing the result view to close the loop and populate result_pk.', primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('dga', 'DGA Simulation'), ('exfil', 'Data Exfiltration'), ('nmap', 'Nmap Reconnaissance')], db_index=True, help_text='Which attack plugin to invoke on the agent. Maps directly to the plugin name in orchestrator dispatch_command().', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current lifecycle state of this task.', max_length=12)),
                ('config_json', models.JSONField(default=dict, help_text='The full parameter dictionary sent from the web UI form and forwarded verbatim to the agent as the command args payload. Stored here so tasks are fully reproducible and auditable. Example for DGA: {"algorithm": "date_seed", "count": 50, "rate": 1.0, "dns_server": null, "seed_secret": "BARC-MIAT"}. Example for Exfil: {"technique": "dns", "profile": "burst", "target": "192.168.1.1", "payload_type": "credentials"}.')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task record was created and the command was dispatched.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the result was received and result_pk was populated. Null until the task reaches COMPLETE or FAILED status.', null=True)),
                ('result_pk', models.IntegerField(blank=True, help_text='Primary key of the result row written to the database once the agent posts its telemetry. Which table this pk references depends on the module field: dga → DGAResult, exfil → ExfilResult, nmap → ScanRequest. Null until status reaches COMPLETE.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Human-readable error detail populated when status transitions to FAILED. May contain the agent exception message, a WebSocket delivery failure reason, or a timeout explanation.')),
                ('agent', models.ForeignKey(help_text='The agent this task was dispatched to.', on_delete=django.db.models.deletion.CASCADE, related_name='module_tasks', to='scanner.agent')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='The web UI user who submitted this task. Null if dispatched via API.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_module_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Task',
                'verbose_name_plural': 'Module Tasks',
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['status', 'module'], name='idx_moduletask_status_module'), models.Index(fields=['agent', 'dispatched_at'], name='idx_moduletask_agent_time')],
            },
        ),
    ]
