# Generated by Django 5.2.13 on 2026-06-15 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_hostresult_options_alter_portfinding_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExfilPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label shown in the payload dropdown.', max_length=128)),
                ('source_type', models.CharField(choices=[('generated', 'Machine Generated'), ('manual', 'Admin Upload')], db_index=True, default='generated', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires.  Set for manual uploads (default 24 h).', null=True)),
                ('payload_type', models.CharField(blank=True, default='credentials', help_text='Template key: credentials / pii / api_key / db_dump / config', max_length=32)),
                ('uploaded_file', models.FileField(blank=True, upload_to='exfil_payloads/%Y/%m/')),
                ('file_size', models.IntegerField(default=0, help_text='Bytes.')),
                ('checksum_sha256', models.CharField(blank=True, help_text='Hex digest of SHA-256 of uploaded_file contents.', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exfil_payloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exfil Payload',
                'verbose_name_plural': 'Exfil Payloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
