# Generated by Django 5.2.13 on 2026-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_exfilpayload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exfilresult',
            name='technique',
            field=models.CharField(choices=[('dns', 'DNS Tunnelling'), ('http', 'HTTP Header Injection'), ('icmp', 'ICMP Payload Stuffing'), ('sqli', 'SQL Injection Exfiltration')], default='dns', max_length=10),
        ),
    ]
